#env: "envLocal"
http_server:
  address: "localhost:7777"
  timeout: 4s
  idle_timeout: 30s
  read_header_timeout: 3s
  user: "myuser"
  password: "mypass"
storage:
  driver: "postgresql"
  host: "localhost"
  port: "5555"
  database: "postgres"
  username: "postgres"
  password: "postgres"
context_timeout: 10s